// This file is auto-generated by drizzle-kit
// It imports the SQL migration files for runtime application

import journal from './meta/_journal.json';
import m0000 from './0000_initial.sql';

export default {
  journal,
  migrations: {
    m0000,
  },
};
